/**
 * Emits src/styles/tokens.hsl.css: the semantic color tokens as HSL channel triples ("40 30% 99%"),
 * the format Tailwind v3 configs consume through `hsl(var(--x) / <alpha-value>)`.
 *
 *   node scripts/color/export-legacy.mts
 *
 * Names mirror tokens.css with an --hsl- prefix. Light values live on :root, dark on .dark and
 * [data-theme="dark"]. Accents are emitted per name under [data-accent=...]; the default accent is on :root.
 */
import { writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { clampChroma, hsl, type Oklch } from "culori"

import { type Appearance, type Ramp } from "./ramps.mts"
import { accent, config, neutral, status, type AccentDef } from "./system.mts"

const here = dirname(fileURLToPath(import.meta.url))
const out = resolve(here, "../../src/styles/tokens.hsl.css")

function channels(c: Oklch): string {
  const h = hsl(clampChroma(c, "oklch"))
  const hue = Math.round(((h.h ?? 0) + 360) % 360)
  const s = Math.min(100, Math.max(0, Math.round((h.s ?? 0) * 1000) / 10))
  const l = Math.min(100, Math.max(0, Math.round(h.l * 1000) / 10))
  return `${hue} ${s}% ${l}%`
}

function semantics(appearance: Appearance, def: AccentDef): [string, string][] {
  const n = neutral(appearance)
  const a = accent(def, appearance)
  const r = n.ramp
  const light = appearance === "light"
  const raised: Oklch = light ? { mode: "oklch", l: 1, c: config.neutral.chroma * 0.3, h: config.neutral.hue } : r[3]
  const st = (k: keyof typeof config.status) => status(k, appearance)
  const rows: [string, Oklch][] = [
    ["bg-page", r[1]],
    ["bg-subtle", r[2]],
    ["bg-surface", light ? r[1] : r[2]],
    ["bg-surface-hover", r[3]],
    ["bg-surface-active", r[4]],
    ["bg-sunken", r[3]],
    ["bg-raised", raised],
    ["fg", n.fg],
    ["fg-secondary", n.fgSecondary],
    ["fg-tertiary", n.fgTertiary],
    ["fg-strong", n.fgStrong],
    ["fg-disabled", r[8]],
    ["fg-inverse", r[1]],
    ["fg-on-accent", r[1]],
    ["border-subtle", r[5]],
    ["border-default", r[6]],
    ["border-strong", r[8]],
    ["border-separator", r[4]],
    ["border-focus", a[9]],
    ["accent-bg", a[3]],
    ["accent-border", a[6]],
    ["accent-solid", a[9]],
    ["accent-solid-hover", a[10]],
    ["accent-text", a[11]],
    ...(["danger", "success", "warning"] as const).flatMap((k): [string, Oklch][] => {
      const ramp: Ramp = st(k)
      return [[`status-${k}-bg`, ramp[3]], [`status-${k}-border`, ramp[6]], [`status-${k}`, ramp[9]], [`status-${k}-text`, ramp[11]]]
    }),
  ]
  return rows.map(([k, c]) => [`--hsl-${k}`, channels(c)])
}

function block(selector: string, rows: [string, string][]) {
  return [`${selector} {`, ...rows.map(([k, v]) => `  ${k}: ${v};`), "}"].join("\n")
}

const def = config.accents[0]
const accentOnly = (rows: [string, string][]) => rows.filter(([k]) => k.startsWith("--hsl-accent") || k === "--hsl-border-focus")

const css = [
  "/* GENERATED by scripts/color/export-legacy.mts from the same config as tokens.css. Do not edit. */",
  "/* HSL channel triples for Tailwind v3: hsl(var(--hsl-bg-page) / <alpha-value>). */",
  block(":root", semantics("light", def)),
  block('.dark, [data-theme="dark"]', semantics("dark", def)),
  ...config.accents.flatMap((a) => [
    block(`[data-accent="${a.name}"]`, accentOnly(semantics("light", a))),
    block(`.dark[data-accent="${a.name}"], [data-theme="dark"][data-accent="${a.name}"], [data-accent="${a.name}"] .dark, [data-accent="${a.name}"] [data-theme="dark"]`, accentOnly(semantics("dark", a))),
  ]),
  [
    "/* Quiet mode: data-quiet on the root. Accent roles collapse into the neutrals. */",
    "[data-quiet] {",
    "  --hsl-border-focus: var(--hsl-fg-strong);",
    "  --hsl-accent-bg: var(--hsl-bg-surface-active);",
    "  --hsl-accent-border: var(--hsl-border-strong);",
    "  --hsl-accent-solid: var(--hsl-fg-strong);",
    "  --hsl-accent-solid-hover: var(--hsl-fg);",
    "  --hsl-accent-text: var(--hsl-fg-strong);",
    "  --hsl-fg-on-accent: var(--hsl-bg-page);",
    "}",
  ].join("\n"),
].join("\n\n")

writeFileSync(out, css + "\n")
console.log(`wrote ${out}`)
